# Generated by Django 5.2.1 on 2025-05-29 18:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoid", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("state", "State"),
                            ("cd119", "Congressional District 119th Congress"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Internal point",
                        null=True,
                        srid=4326,
                        verbose_name="coordinates",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Simplified geometry suitable for thematic mapping.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("geoid", "type"),
                        name="unique__geoid__type",
                    ),
                ],
            },
        ),
    ]
