site_name: Coalition Builder Documentation
site_description: Comprehensive platform for organizing and managing policy advocacy campaigns
site_author: Coalition Builder Team
site_url: https://your-org.github.io/coalition-builder/

repo_name: coalition-builder
repo_url: https://github.com/your-org/coalition-builder
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: getting-started.md

  - User Guides:
      - Content Management: user-guides/content-management.md
      - API Usage: user-guides/api-usage.md
      - Homepage Management: user-guides/homepage.md

  - Development:
      - Setup: development/setup.md
      - Backend: development/backend.md
      - Frontend: development/frontend.md
      - SSR: development/ssr.md
      - Testing: development/testing.md

  - Deployment:
      - AWS Deployment: deployment/aws.md
      - Docker Setup: deployment/docker.md
      - Health Monitoring: deployment/health.md

  - Architecture:
      - System Overview: architecture/overview.md
      - API Design: architecture/api.md
      - Database Schema: architecture/database.md

  - Administration:
      - Terraform Infrastructure: admin/terraform.md
      - CI/CD Workflows: admin/cicd.md
      - Troubleshooting: admin/troubleshooting.md

  - Contributing:
      - Contributing Guide: contributing/guide.md
      - Code Style: contributing/style.md

  - Reference:
      - API Reference: api/index.md
      - Environment Variables: reference/environment.md
      - CLI Commands: reference/cli.md
      - Changelog: reference/changelog.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/coalition-builder
  version:
    provider: mike

# GitHub Pages specific settings
use_directory_urls: true
