# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bioguide_id", models.CharField(max_length=10, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "chamber",
                    models.CharField(
                        choices=[("House", "House"), ("Senate", "Senate")],
                        max_length=10,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("district", models.CharField(blank=True, max_length=2)),
                ("is_senior", models.BooleanField(blank=True, null=True)),
                ("party", models.CharField(max_length=1)),
                ("in_office", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
