# Generated by Django 5.2.1 on 2025-06-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        help_text="Name of the organization",
                        max_length=200,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="Brief tagline or slogan for the organization",
                        max_length=500,
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        help_text="Main headline displayed prominently on the homepage",
                        max_length=300,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        help_text="Optional subtitle or description under the hero title",
                    ),
                ),
                (
                    "hero_background_image",
                    models.URLField(
                        blank=True,
                        help_text="URL to hero background image (optional)",
                    ),
                ),
                (
                    "about_section_title",
                    models.CharField(
                        default="About Our Mission",
                        help_text="Title for the about/mission section",
                        max_length=200,
                    ),
                ),
                (
                    "about_section_content",
                    models.TextField(
                        help_text="Main content describing the organization's mission and goals",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Get Involved",
                        help_text="Title for the call-to-action section",
                        max_length=200,
                    ),
                ),
                (
                    "cta_content",
                    models.TextField(
                        blank=True,
                        help_text="Description for how people can get involved",
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(
                        default="Learn More",
                        help_text="Text for the call-to-action button",
                        max_length=100,
                    ),
                ),
                (
                    "cta_button_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for the call-to-action button",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number (optional)",
                        max_length=20,
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook page URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter/X profile URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, help_text="Instagram profile URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn page URL"),
                ),
                (
                    "campaigns_section_title",
                    models.CharField(
                        default="Policy Campaigns",
                        help_text="Title for the campaigns section",
                        max_length=200,
                    ),
                ),
                (
                    "campaigns_section_subtitle",
                    models.TextField(
                        blank=True,
                        help_text="Optional subtitle for the campaigns section",
                    ),
                ),
                (
                    "show_campaigns_section",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to display the campaigns section on the homepage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this homepage configuration is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Configuration",
                "verbose_name_plural": "Homepage Configurations",
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this content block",
                        max_length=200,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Block"),
                            ("image", "Image Block"),
                            ("text_image", "Text + Image Block"),
                            ("quote", "Quote Block"),
                            ("stats", "Statistics Block"),
                            ("custom_html", "Custom HTML Block"),
                        ],
                        default="text",
                        help_text="Type of content block",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Main content for this block (text, HTML, etc.)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Image URL for image or text+image blocks",
                    ),
                ),
                (
                    "image_alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for the image (accessibility)",
                        max_length=200,
                    ),
                ),
                (
                    "css_classes",
                    models.CharField(
                        blank=True,
                        help_text="Additional CSS classes for styling (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Background color in hex format (e.g., #ffffff)",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this block appears (lower numbers first)",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this block is visible on the homepage",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "homepage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="core.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
