# Generated by Django 5.2.1 on 2025-05-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endorser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("state", models.CharField(max_length=2)),
                ("county", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("waterman", "Waterman"),
                            ("business", "Business"),
                            ("nonprofit", "Nonprofit"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("public_display", models.BooleanField(default=True)),
                ("statement", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="campaigns.policycampaign",
                    ),
                ),
            ],
        ),
    ]
