# Generated by Django 5.2.1 on 2025-06-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField(blank=True)),
                ("public_display", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="campaigns.policycampaign",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="stakeholders.stakeholder",
                    ),
                ),
            ],
            options={
                "unique_together": {("stakeholder", "campaign")},
            },
        ),
    ]
