# Generated by Django 5.2.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("legislators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "chamber",
                    models.CharField(
                        choices=[("House", "House"), ("Senate", "Senate")],
                        max_length=10,
                    ),
                ),
                ("congress_session", models.CharField(max_length=10)),
                ("introduced_date", models.DateField()),
                ("status", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "cosponsors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cosponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="campaigns.policycampaign",
                    ),
                ),
                (
                    "sponsors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
            ],
        ),
    ]
