name: Prettier Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier_lint:
    name: Prettier Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Check Frontend files
        run: |
          cd frontend
          npm run format:check

      - name: Create .prettierignore
        run: |
          echo "node_modules/" > .prettierignore
          echo "build/" >> .prettierignore
          echo "dist/" >> .prettierignore
          echo "coverage/" >> .prettierignore
          echo "frontend/node_modules/" >> .prettierignore
          echo "backend/.venv/" >> .prettierignore

      - name: Check project-wide files
        run: |
          cd frontend
          # Check all relevant files including root directory files and workflow files
          npx prettier --check "../{,**/}*.{md,yml,yaml,json,css}" "../.github/workflows/*.yml" --ignore-path ../.prettierignore
