name: Terraform Lint

on:
  push:
    branches: [main]
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/lint_terraform.yml"
  pull_request:
    branches: [main]
    paths:
      - "terraform/**/*.tf"
      - ".github/workflows/lint_terraform.yml"

jobs:
  terraform_lint:
    name: Terraform Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.48.0

      - name: Run TFLint
        run: |
          cd terraform
          tflint --init
          tflint --recursive
